# test docker compose deploy for local development
#
# @todo run artisan test on the test environment
#
name: Docker Compose Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Environment File
        shell: bash
        run: cp .env.example .env && cp .env.example .env.testing
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env
      - name: Build the stack
        run: docker-compose -p "laravel_restful_api" up -d
