name: Laravel CI
on: [push, pull_request]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: wendyourway/laravel-docker:latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: homestead
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install composer dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing
          php artisan config:cache
          php artisan key:generate
          php artisan route:cache
          php artisan scribe:generate
          php artisan migrate
          php artisan passport:install
          php artisan db:seed
      - name: Run Application
        run: |
          php artisan queue:work >> storage/logs/queue.log &
          php artisan serve &
      - name: Run Tests
        run: |
          php artisan test --env=testing --testsuite=Unit,Feature
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: env
          path: |
            .env
            .env.testing
          retention-days: 5
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: storage/logs/*
          retention-days: 5
